# Generated by Django 4.0.5 on 2022-10-02 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_item_city'),
        ('news', '0003_alter_articles_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.city', verbose_name='city'),
            preserve_default=False,
        ),
    ]
