# Generated by Django 4.0.5 on 2022-10-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titlepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat_item_dropbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropbox', models.CharField(choices=[('1', 'Таганрог'), ('2', 'Ростов-на-Дону'), ('3', 'Москва'), ('4', 'Санкт-Петербург'), ('5', 'Волгоград')], default=1, max_length=20)),
            ],
        ),
    ]
