# Generated by Django 4.0.5 on 2022-10-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titlepage', '0003_cities_dropbox_delete_cat_item_dropbox_delete_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities_dropbox',
            name='dropbox',
            field=models.CharField(choices=[('1', 'Таганрог'), ('2', 'Астрахань')], default=1, max_length=20),
        ),
    ]
