# Generated by Django 4.0.5 on 2022-06-26 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(blank=True, default=0)),
                ('item_image', models.ImageField(upload_to='items/%Y/%m/%d/', verbose_name='image')),
                ('item_title', models.CharField(default='New item', max_length=250, verbose_name='title')),
                ('item_description', models.TextField(default='Some text', verbose_name='description')),
                ('item_address', models.CharField(default='Russia, Moscow, Red square', max_length=250, verbose_name='address')),
                ('mapcode', models.CharField(max_length=30, verbose_name='mapcode')),
                ('item_address_link', models.URLField(verbose_name='address_url')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('author', models.ForeignKey(default='None', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ('rating',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, choices=[('5', 'Отлично'), ('4', 'Хорошо'), ('3', 'Нормально'), ('2', 'Плохо'), ('1', 'Ужасно')], max_length=20, null=True, verbose_name='Value')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='comments/%Y/%m/%d/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('active', 'Active')], default='active', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='items.item')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
