# Generated by Django 4.0.5 on 2022-07-21 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_specialdays_openinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialdays',
            name='closed',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.CreateModel(
            name='FoodBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bread', models.IntegerField()),
                ('potato', models.IntegerField()),
                ('sugar', models.IntegerField()),
                ('milk', models.IntegerField()),
                ('eags', models.IntegerField()),
                ('meat', models.IntegerField()),
                ('oil', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item', verbose_name='food_basked')),
            ],
        ),
    ]
