# Generated by Django 4.0.5 on 2022-09-20 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_medprices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParksIvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ivents_year', models.IntegerField()),
                ('square', models.IntegerField()),
                ('people_day', models.IntegerField()),
                ('cafes', models.IntegerField()),
                ('prices', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item', verbose_name='food_basked')),
            ],
        ),
    ]
