# Generated by Django 4.0.5 on 2022-09-20 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_alter_medprices_item_alter_parksivents_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ege_sr', models.IntegerField()),
                ('number_of_seats', models.IntegerField()),
                ('facultets', models.IntegerField()),
                ('ammounts_budget', models.IntegerField()),
                ('prices_month_sr', models.IntegerField()),
                ('procent_trud', models.IntegerField()),
                ('rating_city', models.IntegerField()),
                ('rating_russia', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item', verbose_name='University_Rate')),
            ],
        ),
        migrations.CreateModel(
            name='SchollRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ege', models.IntegerField()),
                ('number_of_seats', models.IntegerField()),
                ('ammount_class', models.IntegerField()),
                ('ammounts_teather', models.IntegerField()),
                ('prices_month', models.IntegerField()),
                ('ammont_holidays', models.IntegerField()),
                ('rating_city', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item', verbose_name='scholl_Rate')),
            ],
        ),
    ]
