# Generated by Django 4.0.5 on 2022-10-01 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.city', verbose_name='city'),
            preserve_default=False,
        ),
    ]
