# Generated by Django 4.0.5 on 2022-10-03 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_alter_openinghours_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialdays',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='specialdays',
            name='from_hour',
        ),
        migrations.RemoveField(
            model_name='specialdays',
            name='to_hour',
        ),
    ]
