# Generated by Django 4.0.5 on 2022-06-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='images.png', null=True, upload_to='Users/%Y/%m/%d/', verbose_name='image'),
        ),
    ]
