# Generated by Django 4.0.5 on 2022-08-02 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_organisation', models.CharField(max_length=255, verbose_name='name_organ')),
                ('text_questionnaire', models.TextField(verbose_name='text_questionnaire')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('user_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_owner')),
            ],
        ),
    ]
